version: "3.9"

services:
  workspace:
    build:
      context: .
      dockerfile: ./docker/workspace/Dockerfile
    container_name: ts-next-amplify-sample-workspace
    tty: true
    volumes:
      - .:/work/ts-next-amplify-sample
      - ts-next-amplify-sample_node_modules_volume:/work/ts-next-amplify-sample/node_modules
    working_dir: /work/ts-next-amplify-sample
    ports:
      - 4000:3000

volumes:
  ts-next-amplify-sample_node_modules_volume:

networks:
  auth-sample-network:
    external: true
